// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.25.0
// source: isolate.proto

package isolatev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

const (
	IsolateService_CreateSandbox_FullMethodName    = "/isolate.v1.IsolateService/CreateSandbox"
	IsolateService_RunSandbox_FullMethodName       = "/isolate.v1.IsolateService/RunSandbox"
	IsolateService_GetSandbox_FullMethodName       = "/isolate.v1.IsolateService/GetSandbox"
	IsolateService_TerminateSandbox_FullMethodName = "/isolate.v1.IsolateService/TerminateSandbox"
	IsolateService_ListSandboxes_FullMethodName    = "/isolate.v1.IsolateService/ListSandboxes"
	IsolateService_StreamOutput_FullMethodName     = "/isolate.v1.IsolateService/StreamOutput"
	IsolateService_GetMetrics_FullMethodName       = "/isolate.v1.IsolateService/GetMetrics"
)

// IsolateServiceClient is the client API for IsolateService service.
type IsolateServiceClient interface {
	// Create a new sandbox.
	CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error)
	// Run a sandbox.
	RunSandbox(ctx context.Context, in *RunSandboxRequest, opts ...grpc.CallOption) (*RunSandboxResponse, error)
	// Get sandbox status.
	GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error)
	// Terminate a sandbox.
	TerminateSandbox(ctx context.Context, in *TerminateSandboxRequest, opts ...grpc.CallOption) (*TerminateSandboxResponse, error)
	// List all sandboxes.
	ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error)
	// Stream sandbox output.
	StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (IsolateService_StreamOutputClient, error)
	// Get metrics.
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type isolateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewIsolateServiceClient(cc grpc.ClientConnInterface) IsolateServiceClient {
	return &isolateServiceClient{cc}
}

func (c *isolateServiceClient) CreateSandbox(ctx context.Context, in *CreateSandboxRequest, opts ...grpc.CallOption) (*CreateSandboxResponse, error) {
	out := new(CreateSandboxResponse)
	err := c.cc.Invoke(ctx, IsolateService_CreateSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolateServiceClient) RunSandbox(ctx context.Context, in *RunSandboxRequest, opts ...grpc.CallOption) (*RunSandboxResponse, error) {
	out := new(RunSandboxResponse)
	err := c.cc.Invoke(ctx, IsolateService_RunSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolateServiceClient) GetSandbox(ctx context.Context, in *GetSandboxRequest, opts ...grpc.CallOption) (*GetSandboxResponse, error) {
	out := new(GetSandboxResponse)
	err := c.cc.Invoke(ctx, IsolateService_GetSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolateServiceClient) TerminateSandbox(ctx context.Context, in *TerminateSandboxRequest, opts ...grpc.CallOption) (*TerminateSandboxResponse, error) {
	out := new(TerminateSandboxResponse)
	err := c.cc.Invoke(ctx, IsolateService_TerminateSandbox_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolateServiceClient) ListSandboxes(ctx context.Context, in *ListSandboxesRequest, opts ...grpc.CallOption) (*ListSandboxesResponse, error) {
	out := new(ListSandboxesResponse)
	err := c.cc.Invoke(ctx, IsolateService_ListSandboxes_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *isolateServiceClient) StreamOutput(ctx context.Context, in *StreamOutputRequest, opts ...grpc.CallOption) (IsolateService_StreamOutputClient, error) {
	stream, err := c.cc.NewStream(ctx, &IsolateService_ServiceDesc.Streams[0], IsolateService_StreamOutput_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &isolateServiceStreamOutputClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type IsolateService_StreamOutputClient interface {
	Recv() (*OutputChunk, error)
	grpc.ClientStream
}

type isolateServiceStreamOutputClient struct {
	grpc.ClientStream
}

func (x *isolateServiceStreamOutputClient) Recv() (*OutputChunk, error) {
	m := new(OutputChunk)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *isolateServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, IsolateService_GetMetrics_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// IsolateServiceServer is the server API for IsolateService service.
type IsolateServiceServer interface {
	// Create a new sandbox.
	CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error)
	// Run a sandbox.
	RunSandbox(context.Context, *RunSandboxRequest) (*RunSandboxResponse, error)
	// Get sandbox status.
	GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error)
	// Terminate a sandbox.
	TerminateSandbox(context.Context, *TerminateSandboxRequest) (*TerminateSandboxResponse, error)
	// List all sandboxes.
	ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error)
	// Stream sandbox output.
	StreamOutput(*StreamOutputRequest, IsolateService_StreamOutputServer) error
	// Get metrics.
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedIsolateServiceServer()
}

// UnimplementedIsolateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedIsolateServiceServer struct {
}

func (UnimplementedIsolateServiceServer) CreateSandbox(context.Context, *CreateSandboxRequest) (*CreateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSandbox not implemented")
}
func (UnimplementedIsolateServiceServer) RunSandbox(context.Context, *RunSandboxRequest) (*RunSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunSandbox not implemented")
}
func (UnimplementedIsolateServiceServer) GetSandbox(context.Context, *GetSandboxRequest) (*GetSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSandbox not implemented")
}
func (UnimplementedIsolateServiceServer) TerminateSandbox(context.Context, *TerminateSandboxRequest) (*TerminateSandboxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TerminateSandbox not implemented")
}
func (UnimplementedIsolateServiceServer) ListSandboxes(context.Context, *ListSandboxesRequest) (*ListSandboxesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSandboxes not implemented")
}
func (UnimplementedIsolateServiceServer) StreamOutput(*StreamOutputRequest, IsolateService_StreamOutputServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamOutput not implemented")
}
func (UnimplementedIsolateServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedIsolateServiceServer) mustEmbedUnimplementedIsolateServiceServer() {}

// UnsafeIsolateServiceServer may be embedded to opt out of forward compatibility for this service.
type UnsafeIsolateServiceServer interface {
	mustEmbedUnimplementedIsolateServiceServer()
}

func RegisterIsolateServiceServer(s grpc.ServiceRegistrar, srv IsolateServiceServer) {
	s.RegisterService(&IsolateService_ServiceDesc, srv)
}

func _IsolateService_CreateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).CreateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_CreateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).CreateSandbox(ctx, req.(*CreateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolateService_RunSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).RunSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_RunSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).RunSandbox(ctx, req.(*RunSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolateService_GetSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).GetSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_GetSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).GetSandbox(ctx, req.(*GetSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolateService_TerminateSandbox_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TerminateSandboxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).TerminateSandbox(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_TerminateSandbox_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).TerminateSandbox(ctx, req.(*TerminateSandboxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolateService_ListSandboxes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSandboxesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).ListSandboxes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_ListSandboxes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).ListSandboxes(ctx, req.(*ListSandboxesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _IsolateService_StreamOutput_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamOutputRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(IsolateServiceServer).StreamOutput(m, &isolateServiceStreamOutputServer{stream})
}

type IsolateService_StreamOutputServer interface {
	Send(*OutputChunk) error
	grpc.ServerStream
}

type isolateServiceStreamOutputServer struct {
	grpc.ServerStream
}

func (x *isolateServiceStreamOutputServer) Send(m *OutputChunk) error {
	return x.ServerStream.SendMsg(m)
}

func _IsolateService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(IsolateServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: IsolateService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(IsolateServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// IsolateService_ServiceDesc is the grpc.ServiceDesc for IsolateService service.
var IsolateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isolate.v1.IsolateService",
	HandlerType: (*IsolateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSandbox",
			Handler:    _IsolateService_CreateSandbox_Handler,
		},
		{
			MethodName: "RunSandbox",
			Handler:    _IsolateService_RunSandbox_Handler,
		},
		{
			MethodName: "GetSandbox",
			Handler:    _IsolateService_GetSandbox_Handler,
		},
		{
			MethodName: "TerminateSandbox",
			Handler:    _IsolateService_TerminateSandbox_Handler,
		},
		{
			MethodName: "ListSandboxes",
			Handler:    _IsolateService_ListSandboxes_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _IsolateService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamOutput",
			Handler:       _IsolateService_StreamOutput_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "isolate.proto",
}
