// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.0
// source: isolate.proto

package isolatev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Request to create a sandbox.
type CreateSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// WASM module bytes.
	Module []byte `protobuf:"bytes,1,opt,name=module,proto3" json:"module,omitempty"`
	// Sandbox configuration.
	Config *SandboxConfig `protobuf:"bytes,2,opt,name=config,proto3" json:"config,omitempty"`
}

func (x *CreateSandboxRequest) Reset() {
	*x = CreateSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxRequest) ProtoMessage() {}

func (x *CreateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CreateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSandboxRequest) GetModule() []byte {
	if x != nil {
		return x.Module
	}
	return nil
}

func (x *CreateSandboxRequest) GetConfig() *SandboxConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

// Response from creating a sandbox.
type CreateSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Module hash.
	ModuleHash string `protobuf:"bytes,2,opt,name=module_hash,json=moduleHash,proto3" json:"module_hash,omitempty"`
	// Creation time in milliseconds.
	CreationTimeMs float64 `protobuf:"fixed64,3,opt,name=creation_time_ms,json=creationTimeMs,proto3" json:"creation_time_ms,omitempty"`
}

func (x *CreateSandboxResponse) Reset() {
	*x = CreateSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSandboxResponse) ProtoMessage() {}

func (x *CreateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*CreateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSandboxResponse) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *CreateSandboxResponse) GetModuleHash() string {
	if x != nil {
		return x.ModuleHash
	}
	return ""
}

func (x *CreateSandboxResponse) GetCreationTimeMs() float64 {
	if x != nil {
		return x.CreationTimeMs
	}
	return 0
}

// Request to run a sandbox.
type RunSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Optional input data.
	Input []byte `protobuf:"bytes,2,opt,name=input,proto3" json:"input,omitempty"`
	// Entry point function (default: "_start").
	EntryPoint string `protobuf:"bytes,3,opt,name=entry_point,json=entryPoint,proto3" json:"entry_point,omitempty"`
}

func (x *RunSandboxRequest) Reset() {
	*x = RunSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSandboxRequest) ProtoMessage() {}

func (x *RunSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RunSandboxRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{2}
}

func (x *RunSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RunSandboxRequest) GetInput() []byte {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RunSandboxRequest) GetEntryPoint() string {
	if x != nil {
		return x.EntryPoint
	}
	return ""
}

// Response from running a sandbox.
type RunSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Exit code.
	ExitCode int32 `protobuf:"varint,1,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	// Captured stdout.
	Stdout []byte `protobuf:"bytes,2,opt,name=stdout,proto3" json:"stdout,omitempty"`
	// Captured stderr.
	Stderr []byte `protobuf:"bytes,3,opt,name=stderr,proto3" json:"stderr,omitempty"`
	// Execution duration in milliseconds.
	DurationMs float64 `protobuf:"fixed64,4,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	// Resource usage.
	ResourceUsage *ResourceUsage `protobuf:"bytes,5,opt,name=resource_usage,json=resourceUsage,proto3" json:"resource_usage,omitempty"`
}

func (x *RunSandboxResponse) Reset() {
	*x = RunSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RunSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSandboxResponse) ProtoMessage() {}

func (x *RunSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*RunSandboxResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{3}
}

func (x *RunSandboxResponse) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *RunSandboxResponse) GetStdout() []byte {
	if x != nil {
		return x.Stdout
	}
	return nil
}

func (x *RunSandboxResponse) GetStderr() []byte {
	if x != nil {
		return x.Stderr
	}
	return nil
}

func (x *RunSandboxResponse) GetDurationMs() float64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

func (x *RunSandboxResponse) GetResourceUsage() *ResourceUsage {
	if x != nil {
		return x.ResourceUsage
	}
	return nil
}

// Request to get sandbox status.
type GetSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
}

func (x *GetSandboxRequest) Reset() {
	*x = GetSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxRequest) ProtoMessage() {}

func (x *GetSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetSandboxRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{4}
}

func (x *GetSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// Response with sandbox status.
type GetSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox info.
	Sandbox *SandboxInfo `protobuf:"bytes,1,opt,name=sandbox,proto3" json:"sandbox,omitempty"`
}

func (x *GetSandboxResponse) Reset() {
	*x = GetSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSandboxResponse) ProtoMessage() {}

func (x *GetSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetSandboxResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{5}
}

func (x *GetSandboxResponse) GetSandbox() *SandboxInfo {
	if x != nil {
		return x.Sandbox
	}
	return nil
}

// Request to terminate a sandbox.
type TerminateSandboxRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
}

func (x *TerminateSandboxRequest) Reset() {
	*x = TerminateSandboxRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateSandboxRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSandboxRequest) ProtoMessage() {}

func (x *TerminateSandboxRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*TerminateSandboxRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{6}
}

func (x *TerminateSandboxRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

// Response from terminating a sandbox.
type TerminateSandboxResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Whether the sandbox was terminated.
	Terminated bool `protobuf:"varint,1,opt,name=terminated,proto3" json:"terminated,omitempty"`
	// Final metrics.
	Metrics *SandboxMetrics `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *TerminateSandboxResponse) Reset() {
	*x = TerminateSandboxResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TerminateSandboxResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TerminateSandboxResponse) ProtoMessage() {}

func (x *TerminateSandboxResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*TerminateSandboxResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{7}
}

func (x *TerminateSandboxResponse) GetTerminated() bool {
	if x != nil {
		return x.Terminated
	}
	return false
}

func (x *TerminateSandboxResponse) GetMetrics() *SandboxMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Request to list sandboxes.
type ListSandboxesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Optional state filter.
	StateFilter string `protobuf:"bytes,1,opt,name=state_filter,json=stateFilter,proto3" json:"state_filter,omitempty"`
	// Maximum number of results.
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// Pagination offset.
	Offset int32 `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
}

func (x *ListSandboxesRequest) Reset() {
	*x = ListSandboxesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSandboxesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesRequest) ProtoMessage() {}

func (x *ListSandboxesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ListSandboxesRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{8}
}

func (x *ListSandboxesRequest) GetStateFilter() string {
	if x != nil {
		return x.StateFilter
	}
	return ""
}

func (x *ListSandboxesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListSandboxesRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// Response with sandbox list.
type ListSandboxesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// List of sandboxes.
	Sandboxes []*SandboxInfo `protobuf:"bytes,1,rep,name=sandboxes,proto3" json:"sandboxes,omitempty"`
	// Total count.
	Total int32 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
}

func (x *ListSandboxesResponse) Reset() {
	*x = ListSandboxesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListSandboxesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSandboxesResponse) ProtoMessage() {}

func (x *ListSandboxesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ListSandboxesResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{9}
}

func (x *ListSandboxesResponse) GetSandboxes() []*SandboxInfo {
	if x != nil {
		return x.Sandboxes
	}
	return nil
}

func (x *ListSandboxesResponse) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

// Request to stream sandbox output.
type StreamOutputRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	SandboxId string `protobuf:"bytes,1,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	// Which stream(s) to follow.
	FollowStdout bool `protobuf:"varint,2,opt,name=follow_stdout,json=followStdout,proto3" json:"follow_stdout,omitempty"`
	FollowStderr bool `protobuf:"varint,3,opt,name=follow_stderr,json=followStderr,proto3" json:"follow_stderr,omitempty"`
}

func (x *StreamOutputRequest) Reset() {
	*x = StreamOutputRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamOutputRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamOutputRequest) ProtoMessage() {}

func (x *StreamOutputRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*StreamOutputRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{10}
}

func (x *StreamOutputRequest) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *StreamOutputRequest) GetFollowStdout() bool {
	if x != nil {
		return x.FollowStdout
	}
	return false
}

func (x *StreamOutputRequest) GetFollowStderr() bool {
	if x != nil {
		return x.FollowStderr
	}
	return false
}

// A chunk of output.
type OutputChunk struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Stream type: "stdout" or "stderr".
	Stream string `protobuf:"bytes,1,opt,name=stream,proto3" json:"stream,omitempty"`
	// Data.
	Data []byte `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	// Timestamp.
	Timestamp int64 `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
}

func (x *OutputChunk) Reset() {
	*x = OutputChunk{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OutputChunk) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OutputChunk) ProtoMessage() {}

func (x *OutputChunk) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*OutputChunk) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{11}
}

func (x *OutputChunk) GetStream() string {
	if x != nil {
		return x.Stream
	}
	return ""
}

func (x *OutputChunk) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *OutputChunk) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

// Request to get metrics.
type GetMetricsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Format: "prometheus" or "json".
	Format string `protobuf:"bytes,1,opt,name=format,proto3" json:"format,omitempty"`
}

func (x *GetMetricsRequest) Reset() {
	*x = GetMetricsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsRequest) ProtoMessage() {}

func (x *GetMetricsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetMetricsRequest) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{12}
}

func (x *GetMetricsRequest) GetFormat() string {
	if x != nil {
		return x.Format
	}
	return ""
}

// Response with metrics.
type GetMetricsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Metrics data.
	Data string `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetMetricsResponse) Reset() {
	*x = GetMetricsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetMetricsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMetricsResponse) ProtoMessage() {}

func (x *GetMetricsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*GetMetricsResponse) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{13}
}

func (x *GetMetricsResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

// Sandbox configuration.
type SandboxConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Memory limit in bytes.
	MemoryLimit uint64 `protobuf:"varint,1,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	// CPU fuel limit.
	FuelLimit uint64 `protobuf:"varint,2,opt,name=fuel_limit,json=fuelLimit,proto3" json:"fuel_limit,omitempty"`
	// Wall time limit in seconds.
	WallTimeLimitSecs uint32 `protobuf:"varint,3,opt,name=wall_time_limit_secs,json=wallTimeLimitSecs,proto3" json:"wall_time_limit_secs,omitempty"`
	// CPU time limit in seconds.
	CpuTimeLimitSecs uint32 `protobuf:"varint,4,opt,name=cpu_time_limit_secs,json=cpuTimeLimitSecs,proto3" json:"cpu_time_limit_secs,omitempty"`
	// Capabilities to grant.
	Capabilities []*Capability `protobuf:"bytes,5,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	// Environment variables.
	Env map[string]string `protobuf:"bytes,6,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	// Command-line arguments.
	Args []string `protobuf:"bytes,7,rep,name=args,proto3" json:"args,omitempty"`
}

func (x *SandboxConfig) Reset() {
	*x = SandboxConfig{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxConfig) ProtoMessage() {}

func (x *SandboxConfig) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SandboxConfig) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{14}
}

func (x *SandboxConfig) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *SandboxConfig) GetFuelLimit() uint64 {
	if x != nil {
		return x.FuelLimit
	}
	return 0
}

func (x *SandboxConfig) GetWallTimeLimitSecs() uint32 {
	if x != nil {
		return x.WallTimeLimitSecs
	}
	return 0
}

func (x *SandboxConfig) GetCpuTimeLimitSecs() uint32 {
	if x != nil {
		return x.CpuTimeLimitSecs
	}
	return 0
}

func (x *SandboxConfig) GetCapabilities() []*Capability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

func (x *SandboxConfig) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

func (x *SandboxConfig) GetArgs() []string {
	if x != nil {
		return x.Args
	}
	return nil
}

// A capability.
type Capability struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Capability type.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// Capability value (path, host, etc.).
	Value string `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (x *Capability) Reset() {
	*x = Capability{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Capability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Capability) ProtoMessage() {}

func (x *Capability) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*Capability) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{15}
}

func (x *Capability) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Capability) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

// Resource limits.
type ResourceLimits struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MemoryLimit       uint64 `protobuf:"varint,1,opt,name=memory_limit,json=memoryLimit,proto3" json:"memory_limit,omitempty"`
	FuelLimit         uint64 `protobuf:"varint,2,opt,name=fuel_limit,json=fuelLimit,proto3" json:"fuel_limit,omitempty"`
	WallTimeLimitSecs uint32 `protobuf:"varint,3,opt,name=wall_time_limit_secs,json=wallTimeLimitSecs,proto3" json:"wall_time_limit_secs,omitempty"`
	CpuTimeLimitSecs  uint32 `protobuf:"varint,4,opt,name=cpu_time_limit_secs,json=cpuTimeLimitSecs,proto3" json:"cpu_time_limit_secs,omitempty"`
}

func (x *ResourceLimits) Reset() {
	*x = ResourceLimits{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceLimits) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceLimits) ProtoMessage() {}

func (x *ResourceLimits) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ResourceLimits) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{16}
}

func (x *ResourceLimits) GetMemoryLimit() uint64 {
	if x != nil {
		return x.MemoryLimit
	}
	return 0
}

func (x *ResourceLimits) GetFuelLimit() uint64 {
	if x != nil {
		return x.FuelLimit
	}
	return 0
}

func (x *ResourceLimits) GetWallTimeLimitSecs() uint32 {
	if x != nil {
		return x.WallTimeLimitSecs
	}
	return 0
}

func (x *ResourceLimits) GetCpuTimeLimitSecs() uint32 {
	if x != nil {
		return x.CpuTimeLimitSecs
	}
	return 0
}

// Resource usage.
type ResourceUsage struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Peak memory usage in bytes.
	PeakMemory uint64 `protobuf:"varint,1,opt,name=peak_memory,json=peakMemory,proto3" json:"peak_memory,omitempty"`
	// Fuel consumed.
	FuelConsumed uint64 `protobuf:"varint,2,opt,name=fuel_consumed,json=fuelConsumed,proto3" json:"fuel_consumed,omitempty"`
	// CPU time in milliseconds.
	CpuTimeMs float64 `protobuf:"fixed64,3,opt,name=cpu_time_ms,json=cpuTimeMs,proto3" json:"cpu_time_ms,omitempty"`
	// Wall time in milliseconds.
	WallTimeMs float64 `protobuf:"fixed64,4,opt,name=wall_time_ms,json=wallTimeMs,proto3" json:"wall_time_ms,omitempty"`
	// Bytes read.
	BytesRead uint64 `protobuf:"varint,5,opt,name=bytes_read,json=bytesRead,proto3" json:"bytes_read,omitempty"`
	// Bytes written.
	BytesWritten uint64 `protobuf:"varint,6,opt,name=bytes_written,json=bytesWritten,proto3" json:"bytes_written,omitempty"`
}

func (x *ResourceUsage) Reset() {
	*x = ResourceUsage{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ResourceUsage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResourceUsage) ProtoMessage() {}

func (x *ResourceUsage) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*ResourceUsage) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{17}
}

func (x *ResourceUsage) GetPeakMemory() uint64 {
	if x != nil {
		return x.PeakMemory
	}
	return 0
}

func (x *ResourceUsage) GetFuelConsumed() uint64 {
	if x != nil {
		return x.FuelConsumed
	}
	return 0
}

func (x *ResourceUsage) GetCpuTimeMs() float64 {
	if x != nil {
		return x.CpuTimeMs
	}
	return 0
}

func (x *ResourceUsage) GetWallTimeMs() float64 {
	if x != nil {
		return x.WallTimeMs
	}
	return 0
}

func (x *ResourceUsage) GetBytesRead() uint64 {
	if x != nil {
		return x.BytesRead
	}
	return 0
}

func (x *ResourceUsage) GetBytesWritten() uint64 {
	if x != nil {
		return x.BytesWritten
	}
	return 0
}

// Sandbox info.
type SandboxInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Sandbox ID.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Current state.
	State string `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	// Module hash.
	ModuleHash string `protobuf:"bytes,3,opt,name=module_hash,json=moduleHash,proto3" json:"module_hash,omitempty"`
	// Creation timestamp.
	CreatedAt int64 `protobuf:"varint,4,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	// Age in seconds.
	AgeSecs float64 `protobuf:"fixed64,5,opt,name=age_secs,json=ageSecs,proto3" json:"age_secs,omitempty"`
	// Metrics.
	Metrics *SandboxMetrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
}

func (x *SandboxInfo) Reset() {
	*x = SandboxInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxInfo) ProtoMessage() {}

func (x *SandboxInfo) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SandboxInfo) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{18}
}

func (x *SandboxInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SandboxInfo) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SandboxInfo) GetModuleHash() string {
	if x != nil {
		return x.ModuleHash
	}
	return ""
}

func (x *SandboxInfo) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *SandboxInfo) GetAgeSecs() float64 {
	if x != nil {
		return x.AgeSecs
	}
	return 0
}

func (x *SandboxInfo) GetMetrics() *SandboxMetrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// Sandbox metrics.
type SandboxMetrics struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Number of runs.
	RunCount uint64 `protobuf:"varint,1,opt,name=run_count,json=runCount,proto3" json:"run_count,omitempty"`
	// Successful runs.
	SuccessCount uint64 `protobuf:"varint,2,opt,name=success_count,json=successCount,proto3" json:"success_count,omitempty"`
	// Failed runs.
	FailureCount uint64 `protobuf:"varint,3,opt,name=failure_count,json=failureCount,proto3" json:"failure_count,omitempty"`
	// Total run duration in milliseconds.
	TotalRunDurationMs float64 `protobuf:"fixed64,4,opt,name=total_run_duration_ms,json=totalRunDurationMs,proto3" json:"total_run_duration_ms,omitempty"`
	// Last run duration in milliseconds.
	LastRunDurationMs float64 `protobuf:"fixed64,5,opt,name=last_run_duration_ms,json=lastRunDurationMs,proto3" json:"last_run_duration_ms,omitempty"`
}

func (x *SandboxMetrics) Reset() {
	*x = SandboxMetrics{}
	if protoimpl.UnsafeEnabled {
		mi := &file_isolate_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SandboxMetrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SandboxMetrics) ProtoMessage() {}

func (x *SandboxMetrics) ProtoReflect() protoreflect.Message {
	mi := &file_isolate_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

func (*SandboxMetrics) Descriptor() ([]byte, []int) {
	return file_isolate_proto_rawDescGZIP(), []int{19}
}

func (x *SandboxMetrics) GetRunCount() uint64 {
	if x != nil {
		return x.RunCount
	}
	return 0
}

func (x *SandboxMetrics) GetSuccessCount() uint64 {
	if x != nil {
		return x.SuccessCount
	}
	return 0
}

func (x *SandboxMetrics) GetFailureCount() uint64 {
	if x != nil {
		return x.FailureCount
	}
	return 0
}

func (x *SandboxMetrics) GetTotalRunDurationMs() float64 {
	if x != nil {
		return x.TotalRunDurationMs
	}
	return 0
}

func (x *SandboxMetrics) GetLastRunDurationMs() float64 {
	if x != nil {
		return x.LastRunDurationMs
	}
	return 0
}

var File_isolate_proto protoreflect.FileDescriptor

var file_isolate_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0a, 0x69, 0x73, 0x6f, 0x6c, 0x61, 0x74, 0x65, 0x2e, 0x76, 0x31,
}

var file_isolate_proto_rawDescOnce sync.Once
var file_isolate_proto_rawDescData = file_isolate_proto_rawDesc

func file_isolate_proto_rawDescGZIP() []byte {
	file_isolate_proto_rawDescOnce.Do(func() {
		file_isolate_proto_rawDescData = protoimpl.X.CompressGZIP(file_isolate_proto_rawDescData)
	})
	return file_isolate_proto_rawDescData
}

var file_isolate_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_isolate_proto_goTypes = []interface{}{
	(*CreateSandboxRequest)(nil),     // 0: isolate.v1.CreateSandboxRequest
	(*CreateSandboxResponse)(nil),    // 1: isolate.v1.CreateSandboxResponse
	(*RunSandboxRequest)(nil),        // 2: isolate.v1.RunSandboxRequest
	(*RunSandboxResponse)(nil),       // 3: isolate.v1.RunSandboxResponse
	(*GetSandboxRequest)(nil),        // 4: isolate.v1.GetSandboxRequest
	(*GetSandboxResponse)(nil),       // 5: isolate.v1.GetSandboxResponse
	(*TerminateSandboxRequest)(nil),  // 6: isolate.v1.TerminateSandboxRequest
	(*TerminateSandboxResponse)(nil), // 7: isolate.v1.TerminateSandboxResponse
	(*ListSandboxesRequest)(nil),     // 8: isolate.v1.ListSandboxesRequest
	(*ListSandboxesResponse)(nil),    // 9: isolate.v1.ListSandboxesResponse
	(*StreamOutputRequest)(nil),      // 10: isolate.v1.StreamOutputRequest
	(*OutputChunk)(nil),              // 11: isolate.v1.OutputChunk
	(*GetMetricsRequest)(nil),        // 12: isolate.v1.GetMetricsRequest
	(*GetMetricsResponse)(nil),       // 13: isolate.v1.GetMetricsResponse
	(*SandboxConfig)(nil),            // 14: isolate.v1.SandboxConfig
	(*Capability)(nil),               // 15: isolate.v1.Capability
	(*ResourceLimits)(nil),           // 16: isolate.v1.ResourceLimits
	(*ResourceUsage)(nil),            // 17: isolate.v1.ResourceUsage
	(*SandboxInfo)(nil),              // 18: isolate.v1.SandboxInfo
	(*SandboxMetrics)(nil),           // 19: isolate.v1.SandboxMetrics
	nil,                              // 20: isolate.v1.SandboxConfig.EnvEntry
}

func init() { file_isolate_proto_init() }

func file_isolate_proto_init() {
	if File_isolate_proto != nil {
		return
	}
}
