use anyhow::Result;
use clap::Parser;
use colored::*;
use std::path::PathBuf;

use crate::output::*;

#[derive(Parser, Debug)]
pub struct InitArgs {
    /// Project directory (defaults to current directory)
    #[arg(default_value = ".")]
    pub path: PathBuf,

    /// Project name (defaults to directory name)
    #[arg(short, long)]
    pub name: Option<String>,

    /// Include example WASM modules
    #[arg(long, default_value = "true")]
    pub examples: bool,

    /// Overwrite existing files
    #[arg(long)]
    pub force: bool,
}

pub fn init_command(args: InitArgs, quiet: bool) -> Result<()> {
    use std::fs;
    use std::io::Write;

    let project_dir = args.path.canonicalize().unwrap_or_else(|_| args.path.clone());
    let project_name = args.name.unwrap_or_else(|| {
        project_dir
            .file_name()
            .and_then(|n| n.to_str())
            .map(|s| s.to_string())
            .unwrap_or_else(|| "isolate-project".to_string())
    });

    if !quiet {
        print_banner();
        println!("{}", "Initialize Isolate Project".cyan().bold());
        println!("{}", "─".repeat(50).dimmed());
        println!("  Project: {}", project_name.cyan());
        println!("  Directory: {}\n", project_dir.display().to_string().dimmed());
    }

    // Create project directory if it doesn't exist
    if !project_dir.exists() {
        fs::create_dir_all(&project_dir)?;
    }

    // Check for existing config
    let config_path = project_dir.join(".isolate.toml");
    if config_path.exists() && !args.force {
        anyhow::bail!(
            "Project already initialized (found .isolate.toml). Use --force to overwrite."
        );
    }

    // Create .isolate.toml config file
    let config_content = format!(
        r#"# Isolate Project Configuration
# Generated by: isolate init
# Documentation: https://github.com/josedab/isolate

[project]
name = "{}"
version = "0.1.0"

# Default sandbox configuration
[sandbox]
# Memory limit (supports K, M, G suffixes)
memory_limit = "256M"

# Wall-clock timeout in seconds
timeout = 60

# CPU fuel limit (instruction count, 0 = unlimited)
# fuel = 10000000

# CPU time limit in seconds (0 = unlimited)
# cpu_time = 30

# Entry point function
entry_point = "_start"

# Default capabilities to grant
[sandbox.capabilities]
stdout = true
stderr = true
stdin = false
time = false
random = false
dns = false

# Filesystem capabilities (uncomment to enable)
# [sandbox.capabilities.fs]
# read = ["/data"]
# write = ["/tmp"]

# HTTP capabilities (uncomment to enable)
# [sandbox.capabilities.http]
# hosts = ["*.example.com", "api.github.com"]

# Environment variables to pass
[sandbox.env]
# API_KEY = "${{API_KEY}}"

# Command-line arguments
# [sandbox.args]
# values = ["--verbose"]

# Multiple module configurations
# [[modules]]
# name = "main"
# path = "modules/main.wasm"
#
# [[modules]]
# name = "worker"
# path = "modules/worker.wasm"
# memory_limit = "128M"
"#,
        project_name
    );

    let mut config_file = fs::File::create(&config_path)?;
    config_file.write_all(config_content.as_bytes())?;

    if !quiet {
        println!("  {} Created .isolate.toml", "✓".green());
    }

    // Create examples directory with sample WASM modules
    if args.examples {
        let examples_dir = project_dir.join("examples");
        fs::create_dir_all(&examples_dir)?;

        // Minimal valid WASI WASM module that calls proc_exit(0)
        let hello_wasm: &[u8] = &[
            0x00, 0x61, 0x73, 0x6d, // WASM magic
            0x01, 0x00, 0x00, 0x00, // Version 1
            // Type section
            0x01, 0x08, 0x02, 0x60, 0x01, 0x7f, 0x00, 0x60, 0x00, 0x00,
            // Import section: wasi_snapshot_preview1.proc_exit
            0x02, 0x24, 0x01, 0x16, 0x77, 0x61, 0x73, 0x69, 0x5f, 0x73, 0x6e, 0x61, 0x70, 0x73,
            0x68, 0x6f, 0x74, 0x5f, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x31, 0x09, 0x70,
            0x72, 0x6f, 0x63, 0x5f, 0x65, 0x78, 0x69, 0x74, 0x00, 0x00,
            // Function section
            0x03, 0x02, 0x01, 0x01, // Memory section
            0x05, 0x03, 0x01, 0x00, 0x01, // Export section: memory and _start
            0x07, 0x13, 0x02, 0x06, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x02, 0x00, 0x06, 0x5f,
            0x73, 0x74, 0x61, 0x72, 0x74, 0x00, 0x01, // Code section: call proc_exit(0)
            0x0a, 0x08, 0x01, 0x06, 0x00, 0x41, 0x00, 0x10, 0x00, 0x0b,
        ];

        fs::write(examples_dir.join("hello.wasm"), hello_wasm)?;

        if !quiet {
            println!("  {} Created examples/hello.wasm", "✓".green());
        }

        // Create a README for examples
        let examples_readme = r#"# Example WASM Modules

This directory contains example WebAssembly modules for use with Isolate.

## hello.wasm

A minimal WASI module that exits with code 0.

```bash
isolate run examples/hello.wasm --cap-stdout
```

## Building Your Own Modules

You can compile WASM modules from various languages:

### Rust
```bash
cargo build --target wasm32-wasip1 --release
```

### C/C++ (with WASI SDK)
```bash
$WASI_SDK/bin/clang --sysroot=$WASI_SDK/share/wasi-sysroot -o output.wasm input.c
```

### AssemblyScript
```bash
npx asc input.ts -o output.wasm --runtime stub
```

### Go (TinyGo)
```bash
tinygo build -o output.wasm -target wasi input.go
```
"#;
        fs::write(examples_dir.join("README.md"), examples_readme)?;

        if !quiet {
            println!("  {} Created examples/README.md", "✓".green());
        }
    }

    // Create .gitignore
    let gitignore_path = project_dir.join(".gitignore");
    if !gitignore_path.exists() || args.force {
        let gitignore_content = r#"# Isolate project ignores
*.wasm.cache
.isolate-snapshots/
"#;
        fs::write(&gitignore_path, gitignore_content)?;

        if !quiet {
            println!("  {} Created .gitignore", "✓".green());
        }
    }

    if !quiet {
        println!("{}", "─".repeat(50).dimmed());
        println!("\n  {} Project initialized successfully!", "✓".green().bold());
        println!("\n  {}", "Next steps:".yellow().bold());
        println!("    1. Add your WASM modules to the project");
        println!("    2. Configure capabilities in .isolate.toml");
        println!("    3. Run with: {}", "isolate run <module.wasm>".cyan());
        println!("\n  Try the example:");
        println!("    {}", "isolate run examples/hello.wasm --cap-stdout".cyan());
    }

    Ok(())
}
